// Code generated by Kitex v0.7.0. DO NOT EDIT.

package feedservice

import (
	"context"
	feed "douyin-server-rpc/kitex_gen/feed"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedServiceServiceInfo
}

var feedServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedService"
	handlerType := (*feed.FeedService)(nil)
	methods := map[string]kitex.MethodInfo{
		"ListFeed": kitex.NewMethodInfo(listFeedHandler, newFeedServiceListFeedArgs, newFeedServiceListFeedResult, false),
		"Echo":     kitex.NewMethodInfo(echoHandler, newFeedServiceEchoArgs, newFeedServiceEchoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "feed",
		"ServiceFilePath": "idl/feed.thrift",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.0",
		Extra:           extra,
	}
	return svcInfo
}

func listFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*feed.FeedServiceListFeedArgs)
	realResult := result.(*feed.FeedServiceListFeedResult)
	success, err := handler.(feed.FeedService).ListFeed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedServiceListFeedArgs() interface{} {
	return feed.NewFeedServiceListFeedArgs()
}

func newFeedServiceListFeedResult() interface{} {
	return feed.NewFeedServiceListFeedResult()
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {

	realResult := result.(*feed.FeedServiceEchoResult)
	success, err := handler.(feed.FeedService).Echo(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newFeedServiceEchoArgs() interface{} {
	return feed.NewFeedServiceEchoArgs()
}

func newFeedServiceEchoResult() interface{} {
	return feed.NewFeedServiceEchoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListFeed(ctx context.Context, req *feed.FeedRequest) (r *feed.FeedResponse, err error) {
	var _args feed.FeedServiceListFeedArgs
	_args.Req = req
	var _result feed.FeedServiceListFeedResult
	if err = p.c.Call(ctx, "ListFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Echo(ctx context.Context) (r string, err error) {
	var _args feed.FeedServiceEchoArgs
	var _result feed.FeedServiceEchoResult
	if err = p.c.Call(ctx, "Echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
