version: '3'
services:
  redis-master:
    image: redis
    container_name: redis-master
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 2.5s
      timeout: 2s
      retries: 3
    command: redis-server --port 6379

  redis-slave-1:
    image: redis
    container_name: redis-slave-1
    restart: always
    ports:
      - 6380:6380
    command: redis-server --slaveof 172.18.0.1 6379 --port 6380

  redis-slave-2:
    image: redis
    container_name: redis-slave-2
    restart: always
    ports:
      - 6381:6381
    command: redis-server --slaveof 172.18.0.1 6379 --port 6381

  redis-sentinel-1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    restart: always
    volumes:
      - ./sentinel/sentinel1.conf:/home/redis/data/sentinel/sentinel.conf
    command: redis-sentinel /home/redis/data/sentinel/sentinel.conf
    

  redis-sentinel-2:
    image: redis
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    restart: always
    volumes:
      - ./sentinel/sentinel2.conf:/home/redis/data/sentinel/sentinel.conf
    command: redis-sentinel /home/redis/data/sentinel/sentinel.conf
    

  redis-sentinel-3:
    image: redis
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    restart: always
    volumes:
      - ./sentinel/sentinel3.conf:/home/redis/data/sentinel/sentinel.conf
    command: redis-sentinel /home/redis/data/sentinel/sentinel.conf
